#!/data/data/com.vectras.boxvidra/files/distro/bin/sh
export CLASSPATH=/data/data/com.vectras.boxvidra/files/distro/libexec/termux-x11/loader.apk
unset LD_LIBRARY_PATH LD_PRELOAD
exec /system/bin/app_process -Xnoimage-dex2oat / com.vectras.boxvidra.Loader "$@"
